### ISSUE TITLE
Semicolons are not added in .scss files

### ISSUE THREAD

**Issue by wallyzielinski** [kakRostropovich/sublime-emmet-css-from-one-line#3]
First gotta say it: Love the extensions of emmet to CSS.

However, I can't use this as much as I'd like to in most projects because we work mostly in SASS/SCSS files and the semi colons are not being added properly. To use the main example:

`db w100 h150 posa`

converts to:

```
display: block 
width: 100px
height: 150px
position: absolute
```

**Comment by kakRostropovich** [comment]
Hy, Wally!
I'm sorry I so long answering your query.
 Sadly, this is the problem Emmet-plugin, my plugin in this issue depends entirely on Emmet.

**Comment by wallyzielinski** [comment]
Ah, I see! Thanks for letting me know.
